[ANDROID] replace not supported pthread_cancel by equivalent
building the unix code source for Android results in those errors :

```
jni/../cpp/src/platform/android/ThreadImpl.cpp: In member function 'bool OpenZWave::ThreadImpl::Terminate()':
jni/../cpp/src/platform/android/ThreadImpl.cpp:120:28: error: 'pthread_cancel' was not declared in this scope
  pthread_cancel( m_hThread );
                            ^
jni/../cpp/src/platform/android/EventImpl.cpp: In member function 'bool OpenZWave::EventImpl::Wait(int32)':
jni/../cpp/src/platform/android/EventImpl.cpp:212:28: error: 'PTHREAD_CANCEL_ENABLE' was not declared in this scope
     pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, &oldstate);
```

it because the Android libc, bionic does not support pthread_cancel.
It's not a bug, it's a design choice as indicated in their documentation
(libc/doc/OVERVIEW.txt) :

   pthread_cancel() will *not* be supported in Bionic, because doing this would
   involve making the C library significantly bigger for very little
   benefit.

This commit recreate an equivalent of the pthread_cancel feature by
supported pthread functions and signals. The main logic is :

1. Every thread is created with a signal handler installed
2. When we cancel the thread we use pthread_kill allow to send the
   signal only to the targeted thread
3. The signal handler for this thread calls phtread_exit to terminate
   the thread

PTHREAD_CANCEL_ENABLE and PTHREAD_CANCEL_DISABLE are replaced by masking
and unmasking the signal.